module.exports = {
  ERROR: 'ERROR',
  ROOM_CREATED: 'ROOM_CREATED',
  SERVER_NEW_ROOM: 'SERVER_NEW_ROOM',
  SERVER_JOIN_ROOM: 'SERVER_JOIN_ROOM',
  SERVER_NEW_TOPIC: 'SERVER_NEW_TOPIC',
  NEW_USER: 'NEW_USER',
  USER_LEFT: 'USER_LEFT',
  ROOM_JOINED: 'ROOM_JOINED'
};
