module.exports = {
  ERROR: 'ERROR',
  ROOM_CREATED: 'ROOM_CREATED',
  SERVER_NEW_ROOM: 'SERVER_NEW_ROOM',
  SERVER_JOIN_ROOM: 'SERVER_JOIN_ROOM',
  SERVER_NEW_TOPIC: 'SERVER_NEW_TOPIC',
  SERVER_USER_VOTED: 'SERVER_USER_VOTED',
  TOPIC_CREATED: 'TOPIC_CREATED',
  NEW_USER: 'NEW_USER',
  YOU: 'YOU',
  USER_LEFT: 'USER_LEFT',
  ROOM_JOINED: 'ROOM_JOINED',
  USER_VOTED: 'USER_VOTED',
  ALL_USERS_VOTED: 'ALL_USERS_VOTED',
  SERVER_RESET_VOTES: 'SERVER_RESET_VOTES'
};
